{
    'name': 'Default Taxes',
    'version': '15.02.2022',
    'summary': """Default Taxes by J8C""",
    'description': 'Default Taxes by J8C',
    "category": "Sale",
    "author": "J8C",
    'website': 'https://odoo.j8c.com.mx/',
    'depends': ['sale', 'base'],
    'data': [
        'views/contacto_impuesto_view.xml',
    ],
    'license': 'AGPL-3',
    'demo': [],
    'price': 4.99,
    'currency': 'USD',
    "images": ['static/description/i-1.png'],
    'installable': True,
    'auto_install': False,
    'application': False,
}
